<h1><?php echo $this->translate('Список пользователей') ?></h1>
<hr />
<table>
	<tr>
		<th><?php echo $this->translate('Имя') ?></th>
		<th><?php echo $this->translate('Пароль') ?></th>
		<th><?php echo $this->translate('E-mail') ?></th>
	</tr>
<?php foreach ($users as $user) { ?>
	<tr>
		<td><?php echo $this->escapeHtml($user->getUsrName());?></td>
		<td><?php echo $this->escapeHtml($user->getUsrPassword());?></td>
		<td><?php echo $this->escapeHtml($user->getUsrEmail());?></td>
	</tr>
    </br>
<?php } ?>
</table>